remote_theme: fongandrew/hydeout
title: Boston Software Crafters
description: Software Engineers committed to the craft of software engineering.
permalink: /:name
plugins:
  - jekyll-redirect-from
url: Boston-Software-Crafters.github.io
baseurl: /website
